add some version validation to publish

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -7,8 +7,8 @@ on:
 
   workflow_dispatch:
     inputs:
-      dry_run:
-        description: Run publish with --dry-run
+      release_tag:
+        description: Expected release tag
         type: boolean
         default: true
 
@@ -21,6 +21,9 @@ jobs:
     needs: test-and-lint
     runs-on: ubuntu-latest
     steps:
+      - if: ${{ github.event == 'workflow_dispatch' }}
+        run: echo "!! Running from workflow_dispatch is for debug only"
+
       - uses: actions/checkout@v4
 
       - run: corepack enable pnpm
@@ -30,16 +33,31 @@ jobs:
           node-version-file: .nvmrc
           registry-url: https://registry.npmjs.org
 
-      - run: pnpm install --frozen-lockfile
+      - id: get_release_version
+        run: |
+          TAG_VERSION=$(echo "${{ github.event.release.tag_name || inputs.release_tag }}" | awk 'sub(/^v/,"")1')
+          echo "version=${TAG_VERSION}" >> $GITHUB_OUTPUT
 
-      - run: pnpm build
+      - id: get_package_version
+        run: |
+          PACKAGE_VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
+          echo "version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
 
-      - if: ${{ success() && !inputs.dry_run }}
+      - if: ${{ steps.get_release_version.outputs.version != steps.get_package_version.outputs.version }}
+        run: |
+          echo "Invalid package version, expected ${{ steps.get_release_version.outputs.version }}, got ${{ steps.get_package_version.outputs.version }}"
+          exit 1
+
+      - if: ${{ success() }}
+        run: pnpm install --frozen-lockfile
+
+      - if: ${{ success() }}
+        run: pnpm build
+
+      - if: ${{ success() && github.event == 'workflow_dispatch' }}
+        run: npm publish --dry-run
+
+      - if: ${{ success() && github.event_name == 'published' }}
         run: npm publish --access public
-        env:
-          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
-
-      - if: ${{ success() && inputs.dry_run }}
-        run: npm publish --access public --dry-run
         env:
           NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
